# fly.toml app configuration file generated for near-uniswap-agent on 2024-12-18T10:52:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'near-uniswap-agent'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
